export enum EDUCATIONSTATE {
  INCOMPLETE = 'INCOMPLETE',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
}

export enum EDUCATIONDEGREE {
  SECONDARY = 'SECONDARY',
  TERTIARY = 'TERTIARY',
  ACADEMIC = 'ACADEMIC',
  MASTER = 'MASTER',
  DOCTORATE = 'DOCTORATE',
  JOB = 'JOB',
}
