export enum JOBTYPESENIORITY {
  SENIOR = 'SENIOR',
  SEMI_SENIOR = 'SEMI_SENIOR',
  JUNIOR = 'JUNIOR',
  TRAINEE = 'TRAINEE',
  SUPERVISION = 'SUPERVISION',
  MANAGEMENT = 'MANAGEMENT',
  SENIOR_MANAGEMENT = 'SENIOR_MANAGEMENT',
  BUSINESS_MANAGEMENT = 'BUSINESS_MANAGEMENT',
  FREELANCE = 'FREELANCE',
}

export enum JOBTYPETIME {
  FULLTIME = 'FULLTIME',
  PART_TIME = 'PART_TIME',
  FREELANCE = 'FREELANCE',
  PER_HOUR = 'PER_HOUR',
}

export enum JOBTYPELOCATION {
  ON_SITE = 'ON_SITE',
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
}

export enum JOBTYPECONTRACT {
  INDETERMINATE = 'INDETERMINATE',
  EVENTUAL = 'EVENTUAL',
  AUTONOMOUS = 'AUTONOMOUS',
  OTHER_CASE = 'OTHER_CASE',
}

export enum JOBTYPEINCLUSIVE {
  INCLUSIVE = 'INCLUSIVE',
  NOT_INCLUSIVE = 'NOT_INCLUSIVE',
  TO_DEFINE = 'TO_DEFINE',
}

export enum JOBTYPECULTURE {
  DYNAMIC = 'DYNAMIC',
  FLEXIBLE = 'FLEXIBLE',
  VARIOUS = 'VARIOUS',
  HUMAN_VALIUS_PREVAIL = 'HUMAN_VALIUS_PREVAIL',
}
