export enum PROFILETYPE {
  INVITADO = 'INVITADO',
  POSTULANTE_PRESTADOR = 'POSTULANTE_PRESTADOR',
  EMPRESA = 'EMPRESA',
  ONG = 'ONG',
  ADMIN = 'ADMIN',
}

export enum ACCESLEVEL {
  PUBLICO = 10,
  BASICO = 20,
  INTERMEDIO = 30,
  AVANZADO = 40,
  ADMIN = 50,
}
