export enum PROFILETYPE {
  FREELANCER = 'FREELANCER',
  APPLICANT = 'APPLICANT',
  COMPANY = 'EMPRESA',
  ONG = 'ONG',
}

export enum ACCESLEVEL {
  PUBLIC = 10,
  BASIC = 20,
  INTERMEDIATE = 30,
  ADVANCE = 40,
  ADMIN = 50,
}

export enum ROLES {
  ADMIN = 'ADMIN',
  ADMIN_USER = 'ADMIN_USER',
  BASIC = 'BASIC',
}

export enum ID_TYPE {
  DNI = 'DNI',
  CUIL = 'CUIL',
  PASSPORT = 'PASSPORT',
}
