export enum USER_GENERATIONS {
  X = 'X',
  MILLENNIAL = 'MILLENNIAL',
  CENTENNIAL = 'CENTENNIAL',
}

export enum USER_PURPOSES {
  FIRST_JOB = 'FIRST_JOB',
  GROW_PROFESSIONALLY = 'GROW_PROFESSIONALLY',
  RE_ENTER = 'RE_ENTER',
  OFFER_MY_SERVICES = 'OFFER_MY_SERVICES',
  CHALLENGES = 'CHALLENGES',
}

export enum USER_GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum USER_LIMITATION {
  MOBILITY = 'MOBILITY',
  COGNITION = 'COGNITION',
  COMMUNICATION = 'COMMUNICATION',
  VISION = 'VISION',
  HEARING = 'HEARING',
  SELFCARE = 'SELFCARE',
  NOT_APPLY = 'NOT_APPLY',
}

export enum JOB_STATE {
  TENGO_Y_BUSCO = 'TENGO_Y_BUSCO',
  NO_TENGO_Y_BUSCO = 'NO_TENGO_Y_BUSCO',
  NO_TENGO = 'NO_TENGO',
}
